<?php

namespace ContainerHtt5RWe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bo5JGTTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bo5JGTT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Bo5JGTT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\StudentController::add' => ['privates', '.service_locator.Q2kzMMH', 'get_ServiceLocator_Q2kzMMHService', true],
            'App\\Controller\\StudentController::addF' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\StudentController::delete' => ['privates', '.service_locator.NMpAZsP', 'get_ServiceLocator_NMpAZsPService', true],
            'App\\Controller\\StudentController::fetch' => ['privates', '.service_locator.X75U880', 'get_ServiceLocator_X75U880Service', true],
            'App\\Controller\\StudentController::updatee' => ['privates', '.service_locator.BteFir3', 'get_ServiceLocator_BteFir3Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\StudentController:add' => ['privates', '.service_locator.Q2kzMMH', 'get_ServiceLocator_Q2kzMMHService', true],
            'App\\Controller\\StudentController:addF' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\StudentController:delete' => ['privates', '.service_locator.NMpAZsP', 'get_ServiceLocator_NMpAZsPService', true],
            'App\\Controller\\StudentController:fetch' => ['privates', '.service_locator.X75U880', 'get_ServiceLocator_X75U880Service', true],
            'App\\Controller\\StudentController:updatee' => ['privates', '.service_locator.BteFir3', 'get_ServiceLocator_BteFir3Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\StudentController::add' => '?',
            'App\\Controller\\StudentController::addF' => '?',
            'App\\Controller\\StudentController::delete' => '?',
            'App\\Controller\\StudentController::fetch' => '?',
            'App\\Controller\\StudentController::updatee' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\StudentController:add' => '?',
            'App\\Controller\\StudentController:addF' => '?',
            'App\\Controller\\StudentController:delete' => '?',
            'App\\Controller\\StudentController:fetch' => '?',
            'App\\Controller\\StudentController:updatee' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
