<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHtt5RWe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHtt5RWe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHtt5RWe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHtt5RWe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHtt5RWe\App_KernelDevDebugContainer([
    'container.build_hash' => 'Htt5RWe',
    'container.build_id' => 'a95e6e6e',
    'container.build_time' => 1697645170,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHtt5RWe');
